#!/bin/bash

# @author: me@mruse.cn
# @create: 2015.5.11
# @update: 2015.5.11

# ############################################################################
# /etc/init.d/sersync {start|stop|restart}
#
# start:
#   /usr/local/sersync2/sersync2 -n 4 -r -d -o /usr/local/sersync2/confxml.xml
# stop(kill): 
#   ps aux | grep sersync | awk '{print $2}' | xargs kill -9
# ############################################################################

# Define 
SERSYNC_PATH="/usr/local/sersync2/"
SERSYNC_BIN="$SERSYNC_PATH/sersync2"
SERSYNC_CONF="$SERSYNC_PATH/confxml.xml"
is_running="ps aux | grep sersync | grep -v grep"

start
{
  [ "is_running" != "" ] && echo -e "\"Sersync is already running...\""
  [ "is_running" != "" ] && exit 1
  
  $SERSYNC_BIN -n 4 -r -d -o $SERSYNC_CONF
}

stop
{
  [ "is_running" != "" ] || echo -e "Sersync is not running..."
  [ "is_running" != "" ] || exit 1
  
  ps aux | grep -v grep | grep sersync | awk '{print $2}' | xargs kill -9
}

restart
{
  stop
  start
}
